- id: b9047cf84ccc44a3b194cfa115eaca8d
  alias: Boot completed
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      data:
        subtitle: System state
      message: Boot completed ✅
    service: notify.hb_tel
  mode: single
- id: 6ed8f74c2eff495e97aada68d511183f
  alias: Shutdown initiated completed
  trigger:
  - platform: homeassistant
    event: shutdown
  action:
  - service: notify.hb_tel
    data:
      message: Shutting down.
      data:
        subtitle: System state
  mode: single
- id: '1594127240826'
  alias: Update location
  description: Based on GPS module
  trigger:
  - minutes: '5'
    platform: time_pattern
  condition: []
  action:
  - service: device_tracker.see
    data:
      dev_id: herbertje
      gps:
      - '{{ states.sensor.gps.attributes.latitude }}'
      - '{{ states.sensor.gps.attributes.longitude }}'
    enabled: false
  - service: homeassistant.set_location
    data_template:
      latitude: '{{ states.sensor.gps.attributes.latitude }}'
      longitude: '{{ states.sensor.gps.attributes.longitude }}'
  mode: single
- id: '1596441880593'
  alias: Battery low - notification
  description: ''
  trigger:
  - below: '11.0'
    entity_id: sensor.accuspanning
    platform: numeric_state
  condition: []
  action:
  - data:
      data:
        subtitle: Energy state
      message: "Low battery\U0001F50B shutting down soon."
    service: notify.hb_tel
  mode: single
- id: '1596442014439'
  alias: Battery low - shutdown
  description: Will shutdown NodeMCU's and raspberry on low battery
  trigger:
  - below: '10.8'
    entity_id: sensor.accuspanning
    platform: numeric_state
  condition: []
  action:
  - data:
      data:
        subtitle: Energy state
      message: "Low battery\U0001F50B shutting down now!"
    service: notify.hb_tel
  - data: {}
    entity_id: switch.rechtsboven_shutdown, switch.linksboven_shutdown, switch.accu_monitor_shutdown
    service: switch.turn_on
  - data: {}
    service: shell_command.halt
  mode: single
- id: '1596719819457'
  alias: Notify GPS location
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      data:
        subtitle: Testdata
      message: '{{ state_attr(''sensor.gps'', ''latitude'') }}, {{ state_attr(''sensor.gps'',
        ''longitude'') }}'
    service: notify.hb_tel
  mode: single
- id: '1598814983413'
  alias: Wand uit, leeslamp uit
  description: ''
  trigger:
  - entity_id: group.sides
    platform: state
    to: 'off'
  - platform: state
    entity_id:
    - light.wand_links
    - light.wand_rechts
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.leeslamp_links
    service: light.turn_off
  - data: {}
    entity_id: light.leeslamp_rechts
    service: light.turn_off
  mode: single
- id: '1623933077080'
  alias: Long press shutdown
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: b509a9f74cee82ec486f7586d3d21e09
    entity_id: binary_sensor.links_button_1
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - type: turned_on
    platform: device
    device_id: 9833969faa1064e9297f0ef3013cbaa3
    entity_id: binary_sensor.rechts_button_1
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - scene: scene.pulse
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: light.turn_on
    data:
      brightness: 200
      effect: none
      transition: 5
    target:
      entity_id:
      - light.links_button_1_led
      - light.links_button_2_led
      - light.rechts_button_1_led
      - light.rechts_button_2_led
  - service: switch.turn_on
    target:
      entity_id:
      - switch.accu_monitor_shutdown
      - switch.linksboven_shutdown
      - switch.rechtsboven_shutdown
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: shell_command.halt
    data: {}
  mode: single
- id: '1665425518140'
  alias: Periodic backup
  description: Call backup script each monday on 2am
  trigger:
  - platform: time
    at: 02:00:00
  condition:
  - condition: time
    weekday:
    - mon
  action:
  - service: backup.create
    data: {}
  mode: single
- id: '1666263105048'
  alias: gpsd restart
  description: restart gpsd if there's no gps location
  trigger:
  - platform: numeric_state
    entity_id: sensor.gps
    for:
      hours: 0
      minutes: 10
      seconds: 0
    attribute: latitude
    above: -0.1
    below: 0.1
    value_template: ''
  condition: []
  action:
  - service: shell_command.restart_gpsd
    data: {}
  mode: single
- id: '1686217243622'
  alias: Scene cycle
  description: automation to cycle through list of scenes triggered by button
  trigger:
  - type: turned_on
    platform: device
    device_id: c4068cc5c54c348e6e40f48afd30837a
    entity_id: binary_sensor.links_button_1
    domain: binary_sensor
  - type: turned_on
    platform: device
    device_id: cf6b1a441928c0a76343fee507569855
    entity_id: binary_sensor.rechts_button_1
    domain: binary_sensor
  condition: []
  action:
  - service: input_select.select_next
    data:
      cycle: true
    target:
      entity_id: input_select.scene_selector
  - service: scene.turn_on
    target:
      entity_id: '{{ states(''input_select.scene_selector'') }}'
  mode: single
- id: '1686688089514'
  alias: '[CYCLE] Charge or voltage low - charge on - lights off'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.accu_total_charge_meter
    below: 1
    enabled: false
  - platform: numeric_state
    entity_id: sensor.accuspanning
    below: 11
  condition: []
  action:
  - type: turn_on
    device_id: ef9044ce1940d90f8772b49a5044d4e0
    entity_id: switch.accu_charge
    domain: switch
  - service: scene.turn_on
    target:
      entity_id: scene.nacht
    metadata: {}
  - service: shell_command.halt
    data: {}
  mode: single
- id: '1686688152066'
  alias: '[CYCLE] Cell voltage > 3,55 - charge off - lights on'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.accu_power
    below: 50
    enabled: false
  - platform: numeric_state
    entity_id: sensor.accu_cell_voltages_max
    above: 3.55
  condition: []
  action:
  - type: turn_off
    device_id: ef9044ce1940d90f8772b49a5044d4e0
    entity_id: switch.accu_charge
    domain: switch
  - service: scene.turn_on
    target:
      entity_id: scene.wit
    metadata: {}
    enabled: false
  mode: single
- id: '1686689289319'
  alias: Voltage delta > 0,01 - balancer on
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.accu_cell_voltages_delta
    above: 0.01
  condition: []
  action:
  - type: turn_on
    device_id: 2fbb4311c7edd58c024469aff63101e1
    entity_id: switch.battery_balancer
    domain: switch
  mode: single
- id: '1686689421410'
  alias: accu voltage delta < 0,005 - balancer off
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.accu_cell_voltages_delta
    below: 0.005
  condition: []
  action:
  - type: turn_off
    device_id: 2fbb4311c7edd58c024469aff63101e1
    entity_id: switch.battery_balancer
    domain: switch
  mode: single
- id: '1686691056796'
  alias: '[CYCLE] accuspanning > 14 - accu charge en scene wit aan'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.accuspanning
    above: 14
    for:
      hours: 0
      minutes: 0
      seconds: 1
  condition: []
  action:
  - type: turn_on
    device_id: ef9044ce1940d90f8772b49a5044d4e0
    entity_id: switch.accu_charge
    domain: switch
  - service: scene.turn_on
    target:
      entity_id: scene.wit
    metadata: {}
  mode: single
- id: '1693598015081'
  alias: Laden
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.laden
  condition: []
  action:
  - if:
    - condition: state
      entity_id: binary_sensor.laden
      state: ''
    then:
    - service: scene.turn_on
      target:
        entity_id: scene.laden
      metadata: {}
    else:
    - service: scene.turn_on
      target:
        entity_id: scene.ontladen
      metadata: {}
  mode: single
