services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - .:/config
      - /etc/localtime:/etc/localtime:ro
      - ../containerpipe:/containerpipe
    restart: unless-stopped
    privileged: true
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - ./esphome:/config
      - ./secrets.yaml:/config/secrets.yaml
      - /etc/localtime:/etc/localtime:ro
      - esphomecache:/cache
    ports:
      - 6052:6052
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  batmon-ha:
    container_name: batmon_ha
    image: joosthb/batmon_ha
    restart: unless-stopped
    privileged: true
    volumes:
      - ./options.json:/data/options.json
      - /var/run/dbus/:/var/run/dbus/:z
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883/tcp"
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./mqtt:/mosquitto/config
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  wpawebapp:
    container_name: wpawebapp
    image: joosthb/wpawebapp
    restart: unless-stopped
    ports:
      - "8000:8000/tcp"
    volumes:
      - /etc/wpa_supplicant/wpa_supplicant-wlan1.conf:/app/wpa_supplicant.conf
      - ~/containerpipe:/containerpipe
      - ./connections.db:/app/connections.db
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
volumes:
    esphomecache:
