# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  internal_url: "http://hass.herbert"

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.42.0.0/24 
    - 192.168.0.0/16 
