esphome:
  name: linksboven
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_passwd
  # use_address: linksboven.local
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "linksboven"
    password: !secret device_passwd

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret device_passwd

ota:
  password: !secret device_passwd

binary_sensor:
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLUP
      inverted: True
    name: "Links - Button 1"
    # on_press:
    #   then:
    #     - light.toggle: ledstrip
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: True
    name: "Links - Button 2"
    on_press:
      then:
        - light.toggle: ledstrip
    on_double_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - light.turn_on:
            id: keukenstrip
            brightness: 100%
            red: 100%
            green: 100%
            blue: 100%

# configuration entry
light:
  - platform: monochromatic
    name: "Links - Button 1 LED"
    output: output_component1
    id: led1
    restore_mode: ALWAYS_ON
    effects:
      - pulse:
      - strobe:
          name: blink
          colors:
            - state: true
              duration: 500ms
            - state: false
              duration: 500ms
  - platform: monochromatic
    name: "Links Button 2 LED"
    output: output_component2
    id: led2
    restore_mode: ALWAYS_ON
    effects:
      - pulse:
      - strobe:
          name: blink
          colors:
            - state: true
              duration: 500ms
            - state: false
              duration: 500ms

  - platform: neopixelbus
    variant: WS2811
    type: GRB
    id: ledstrip
    pin: GPIO3
    num_leds: 175
    name: "Wand links"
    effects:
      - addressable_rainbow:
      - random:
          name: "Fast Random"
          transition_length: 4s
          update_interval: 5s
      - addressable_scan:
          name: Scan
          move_interval: 10ms
          scan_width: 10
  - platform: partition
    name: Keuken
    id: keukenstrip
    segments:
      - id: ledstrip
        from: 0
        to: 68
  - platform: partition
    name: Leeslamp links
    id: lezenlinks
    segments:
      - id: ledstrip
        from: 145
        to: 174
            
# output entry
output:
  - platform: esp8266_pwm
    id: output_component1
    pin: D3
  - platform: esp8266_pwm
    id: output_component2
    pin: D4
    
switch:
  - platform: shutdown
    name: "Linksboven shutdown"