esphome:
  name: rechtsboven
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_passwd
  domain: !secret domain
  # use_address: rechtsboven.local
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "rechtsboven"
    password: !secret device_passwd

captive_portal:

# Enable logging
logger:

api:
  encryption:
    key: !secret device_key
    
ota:
  password: !secret device_passwd

binary_sensor:
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLUP
      inverted: True
    name: "Rechts - Button 1"
    # on_press:
    #   then:
    #     - light.toggle: ledstrip
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: True
    name: "Rechts - Button 2"
    on_press:
      then:
        - light.toggle: ledstrip
    on_double_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - light.toggle: spots

# configuration entry
light:
  - platform: monochromatic
    name: "Rechts - Button 1 LED"
    output: output_component1
    id: led1
    restore_mode: ALWAYS_ON
    effects:
      - pulse:
      - strobe:
          name: blink
          colors:
            - state: true
              duration: 500ms
            - state: false
              duration: 500ms
  - platform: monochromatic
    name: "Rechts - Button 2 LED"
    output: output_component2
    id: led2
    restore_mode: ALWAYS_ON
    effects:
      - pulse:
      - strobe:
          name: blink
          colors:
            - state: true
              duration: 500ms
            - state: false
              duration: 500ms
  - platform: binary
    name: "Spots"
    output: output_component3
    id: spots

  - platform: neopixelbus
    type: GRB
    variant: WS2811
    id: ledstrip
    pin: GPIO3
    num_leds: 102
    name: "Wand rechts"
    effects:
      - addressable_rainbow:
      - random:
          name: "Fast Random"
          transition_length: 4s
          update_interval: 5s
      - addressable_scan:
          name: Scan
          move_interval: 10ms
          scan_width: 10
  - platform: partition
    name: Leeslamp rechts
    id: lezenrechts
    segments:
      - id: ledstrip
        from: 72
        to: 101
            
# output entry
output:
  - platform: esp8266_pwm
    id: output_component1
    pin: D3
  - platform: esp8266_pwm
    id: output_component2
    pin: D4
  - platform: gpio
    id: output_component3
    pin: D5
    inverted: true

switch:
  - platform: shutdown
    name: "Rechtsboven shutdown"